### ISSUE TITLE
Reader crashes trying to read files with 0 stripes.

### ISSUE THREAD

**Issue by asandryh** [hortonworks/orc#177] opened 2015-04-27 17:07 UTC

**Comment by omalley** [comment] 2015-04-27 20:46
This is a duplicate of #173 .

**Comment by asandryh** [comment] 2015-04-27 21:29
Oh, great. I'll be careful when the time comes to merge 'vertica' into the main branch.

**Comment by omalley** [comment] 2015-04-27 21:54
You should replace your patch with my patch for #173.

**Closed** 2015-04-29 15:49 UTC
Labels: bug
